version: '3.8'

services:
  comfyui:
    image: ghcr.io/pccr10001/comfyui-gfx1151-fa:260109
    container_name: comfyui_rocm
    stdin_open: true
    tty: true
    user: "${CUID}:${CGID}"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
    devices:
      - /dev/kfd
      - /dev/dri
    
    group_add: # check with `id` command
      - "${VIDEO_GID}"
      - "${RENDER_GID}"
 
    ipc: host
    shm_size: 8G
    
    environment:
      - PYTORCH_TUNABLEOP_ENABLED=0
      - ROCBLAS_USE_HIPBLASLT=1
      - TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1 
    ports:
      - "8188:8188"
    
    volumes:
      - ./ComfyUI:/opt/ComfyUI
      - ./venv:/opt/.venv
    
    restart: unless-stopped
    command: ["--listen", "0.0.0.0", "--use-flash-attention", "--gpu-only"]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188"]
      interval: 30s
      timeout: 30s
      retries: 3
